apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-service
rules:
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - update
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-service
subjects:
  - kind: ServiceAccount
    name: api-service
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      name: api-service
      labels:
        app: api-service
        version: v1
    spec:
      containers:
      - name: api-service
        image: REG/IMAGE:TAG
        imagePullPolicy: Always
        resources:
          requests:
            memory: "7Gi"
            cpu: "450m"
          limits:
            memory: "7.2Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /mnt/data/api-service/
            name: efs-prod-claim
          - mountPath: /mnt/pitcher-2.0/
            name: efs-prod-claim
        ports:
        - containerPort: 8080
        env:
          - name: VERSION
            value: "v1"
      volumes:
        - name: efs-prod-claim
          persistentVolumeClaim:
            claimName: efs-prod-claim
      serviceAccountName: api-service
      
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: api-service
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
